### ISSUE TITLE
Extension Fails to Register Searches Due to Microsoft Patch on Bing URL

### ISSUE THREAD

**Issue by Chappie18** [MeetBhingradiya/MSR-Toolkit#1]
After recent Microsoft updates, extension search fails to register due to changes in Bing URL structure. This disrupts search functionality, impacting user experience

for the search "microsoft rewards"
![image](https://github.com/MeetBhingradiya/MSR-Toolkit/assets/67442659/e79a2fc1-6694-4894-8156-486b1e4febee)

for the seacrh "microsoft xbox"
![image](https://github.com/MeetBhingradiya/MSR-Toolkit/assets/67442659/ae01ebfc-3766-4ab1-a3d8-db1d986b305e)

**Comment by MeetBhingradiya** [comment]
I trying to investigate URL Settings on ABS Core.

I am creating 3.0 for this extension for non extension detection on search of any website.

Give what version you are using and which plan you have with screenshot

**Comment by MeetBhingradiya** [comment]
+ Issue Was Fixed in Local Dev Server.
+ I Update this within 2 days due to some other bugs detected (Mobile Search Not Working & 2.9 Not enable Chrome dev Page)
