### ISSUE TITLE
Unable to do search

### ISSUE THREAD

**Issue by hamzag250** [MeetBhingradiya/MSR-Toolkit#3]
When i use the search, it not work and this appear
<img width="27" alt="image" src="https://github.com/MeetBhingradiya/MSR-Toolkit/assets/75929914/6c6e34ea-760d-4ff1-85c0-8b70974aa04e">

**Comment by MeetBhingradiya** [comment]
+ Don't Open duplicate issue.
+ I giving update today for this issue someone already reported to me see below link

[Issue Link](https://github.com/MeetBhingradiya/MSR-Toolkit/issues/1)
