### ISSUE TITLE
MSR_Toolkit_2.9 ZIP Is Corrupted  

### ISSUE THREAD

**Issue by STRK-ND** [MeetBhingradiya/MSR-Toolkit#4]
I am Unable To extract the MSR_Toolkit_2.9 ZIP While extracting I am getting unexpected end of data.

**Comment by MeetBhingradiya** [comment]
+ Due to Microsoft Bing URL Structure Update I been working for 2.10 that i release today that works.
+ Redownload ZIP it's working fine i downloaded again but nothing wrong.

**Comment by STRK-ND** [comment]
! C:\Users\rajat\Downloads\Compressed\MSR_Toolkit_2.9.zip: The archive is corrupt

![image](https://github.com/MeetBhingradiya/MSR-Toolkit/assets/50959267/81d97d3d-99d8-4d72-a438-e3bfe0c269e2)

**Comment by STRK-ND** [comment]
I am Using Edge and WinRAR , But still facing

**Comment by MeetBhingradiya** [comment]
Download Link in Readme but still i provide heare

[LINK](https://msrtoolkit.vercel.app/api/download)

**Comment by MeetBhingradiya** [comment]
If Problem still Persist Consider problem bansed on Your DNS Provider or use VPN for download

Chrome Settings > Search for DNS

**Comment by STRK-ND** [comment]
![image](https://github.com/MeetBhingradiya/MSR-Toolkit/assets/50959267/2c1a1a7c-f8e1-4f6d-82ef-609ead11bcb9)

**Comment by MeetBhingradiya** [comment]
Rename your folder name with "MSR-TOOLKIT"

This error cased due to dot "." name of your folder

**Comment by STRK-ND** [comment]
I have tried Renaming Prossess but it did not work, Same Error I received of "Could not load options page 'options.html'"

![image](https://github.com/MeetBhingradiya/MSR-Toolkit/assets/50959267/936b0bbb-f90d-40c6-9631-ffc93340269d)

**Comment by MeetBhingradiya** [comment]
You Deleted any files in Folder ?

![image](https://github.com/MeetBhingradiya/MSR-Toolkit/assets/102130001/5be42009-b5bd-4864-b259-df906fd1ff7b)

+ Chek your folder if missing any folder or files maybe not work your extension perfectly. 
+ Re download ZIP from Download Link
